[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/kshvakov/clickhouse"
  version = "1.3.5"

[[constraint]]
  branch = "PMM-3514-group-by-digest-user-host-db-server"
  name = "github.com/percona/go-mysql"
